export default [
  {
    $id: '',
    zipCode: '',
    title: "Modern Family Home",
    description: "A perfect home for a modern family, situated in a quiet suburban neighborhood.",
    price: 350000,
    status: "For-Sale",
    bedrooms: 4,
    bathrooms: 3,
    squareMeters: 200,
    features: ["Garage", "Backyard", "Solar Panels"],
    coverImage: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    images: ["modern-home1.jpg", "modern-home2.jpg", "modern-home3.jpg"],
    city: "Springfield",
    country: "USA",
  },
  {
    $id: '',
    zipCode: '',
    title: "Luxury Apartment",
    description: "A high-end luxury apartment located in the heart of the city.",
    price: 750000,
    status: "For-Sale",
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 150,
    features: ["Rooftop Pool", "Gym", "24/7 Security"],
    coverImage: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    images: ["luxury-apartment1.jpg", "luxury-apartment2.jpg"],
    city: "New York",
    country: "USA",
  },
  {
    $id: '',
    zipCode: '',
    title: "Beachfront Villa",
    description: "A stunning villa right on the beach, offering breathtaking ocean views.",
    price: 1250000,
    status: "Sold",
    bedrooms: 5,
    bathrooms: 4,
    squareMeters: 350,
    features: ["Private Beach", "Infinity Pool", "Terrace"],
    coverImage: "https://images.pexels.com/photos/259685/pexels-photo-259685.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    images: ["beachfront-villa1.jpg", "beachfront-villa2.jpg"],
    city: "Miami",
    country: "USA",
  },
  {
    $id: '',
    zipCode: '',
    title: "Urban Studio",
    description: "Compact and functional studio apartment for young professionals.",
    price: 95000,
    status: "For-Sale",
    bedrooms: 1,
    bathrooms: 1,
    squareMeters: 35,
    features: ["High-Speed Internet", "City View"],
    coverImage: "https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    images: ["urban-studio1.jpg", "urban-studio2.jpg"],
    city: "Seattle",
    country: "USA",
  },
  {
    $id: '',
    zipCode: '',
    title: "Mountain Cabin",
    description: "Secluded mountain cabin with a cozy and serene atmosphere.",
    price: 200000,
    status: "For-Sale",
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 120,
    features: ["Hiking Trails", "Wood Stove", "Deck"],
    coverImage: "https://images.pexels.com/photos/276593/pexels-photo-276593.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    images: ["mountain-cabin1.jpg", "mountain-cabin2.jpg"],
    city: "Boulder",
    country: "USA",
  },
  {
    $id: '',
    zipCode: '',
    title: "Historic Townhouse",
    description: "A beautifully restored townhouse in a historic district.",
    price: 500000,
    status: "Sold",
    bedrooms: 4,
    bathrooms: 3,
    squareMeters: 180,
    features: ["Original Woodwork", "Balcony", "Walkable Neighborhood"],
    coverImage: "https://images.pexels.com/photos/2183521/pexels-photo-2183521.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    images: ["historic-townhouse1.jpg", "historic-townhouse2.jpg"],
    city: "Savannah",
    country: "USA",

  }, {
    $id: '',
    zipCode: '',
    title: "Cozy Cottage",
    description: "A charming cottage in the countryside, perfect for a weekend retreat.",
    price: 120000,
    status: "For-Sale",
    bedrooms: 2,
    bathrooms: 1,
    squareMeters: 80,
    features: ["Fireplace", "Garden", "Rustic Design"],
    coverImage: "https://images.pexels.com/photos/453201/pexels-photo-453201.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    images: ["cozy-cottage1.jpg", "cozy-cottage2.jpg"],
    city: "Asheville",
    country: "USA",
  },

];
